package org.kit.furia.fragment.soot.representation.internal;

/* 
   Generated from furiaConstructDefinitions.vm
   DO NOT EDIT THIS FILE (* x *)V
   "Runtime.availableProcessors()"
*/

public class FuriaConstructDefinitions {
									
	// TODO: add symbols like $ ^ & to the following three
	// slice names so that all the names are one character long
	// this can help us a lot later
	// just don't use ,  (  - . 
	public static final String FURIA_forbin = "$";
	public static final String FURIA_fand = "%";
	public static final String FURIA_fxor = "^";
	public static final String FURIA_fself = "|";
	public static final String FURIA_fshl = "e";
	public static final String FURIA_fcaughtException = "f";
	public static final String FURIA_flt = "g";
	public static final String FURIA_fle = "h";
	public static final String FURIA_fgt = "i";
	public static final String FURIA_fge = "j";
	public static final String FURIA_feq = "k";
	public static final String FURIA_fbooleanConstant = "l";
	public static final String FURIA_fcmpl = "m";
	public static final String FURIA_fcmpg = "n";
	public static final String FURIA_fcmp = "o";
	public static final String FURIA_fphi = "p";
	public static final String FURIA_fushr = "q";
	public static final String FURIA_fthrow = "r";
	public static final String FURIA_fnewInvoke = "s";
	public static final String FURIA_finvoke = "t";
	public static final String FURIA_fexitMonitor = "u";
	public static final String FURIA_fenterMonitor = "v";
	public static final String FURIA_fnewMultiArray = "w";
	public static final String FURIA_fshr = "x";
	public static final String FURIA_finstanceof = "y";
	public static final String FURIA_fnewArray = "z";
	public static final String FURIA_frem = "A";
	public static final String FURIA_fclassConstant = "B";
	public static final String FURIA_fne = "C";
	public static final String FURIA_fneg = "D";
	public static final String FURIA_flength = "E";
	public static final String FURIA_fnew = "F";
	public static final String FURIA_fspecialInvoke = "G";
	public static final String FURIA_fstaticFieldRef = "H";
	public static final String FURIA_flongConstant = "I";
	public static final String FURIA_fmul = "J";
	public static final String FURIA_fstaticInvoque = "K";
	public static final String FURIA_fsub = "L";
	public static final String FURIA_fthisRef = "M";
	public static final String FURIA_ffloatConstant = "N";
	public static final String FURIA_fnull = "O";
	public static final String FURIA_fdoubleConstant = "P";
	public static final String FURIA_fsum = "Q";
	public static final String FURIA_fdiv = "R";
	public static final String FURIA_fcast = "S";
	public static final String FURIA_ftype = "T";
	public static final String FURIA_finstanceFieldRef = "U";
	public static final String FURIA_farrayRef = "V";
	public static final String FURIA_fparameterRef = "W";
	public static final String FURIA_ffieldRef = "X";
	public static final String FURIA_fmethodRef = "Y";
	public static final String FURIA_finterfaceInvoke = "Z";
	public static final String FURIA_fvirtualInvokeExpr = "d" ;
	public static final String FURIA_fstringConstant = "c" ;
	public static final String FURIA_fintConstant = "b" ;
	public static final String FURIA_flocalRef = "a";
	

}

